apiVersion: v1
kind: Service
metadata:
  name: async-guid-api
  namespace: eddie-poc
  labels:
    app: async-guid-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
  selector:
    app: async-guid-api